# THIS CONFIG FILE HAS NOT EFFECT ON THE MODEL; WORK IN PROGRESS

scenario:
  start: '2022-02-01'
  end: '2022-02-28'

solver: 'gurobi'

tech_colors:
  nuclear: "#549ca2"
  biomass: "#dbc263"
  interconnector: "#dd75b0"
  onwind: "#7ac677"
  offwind: "#6895dd"
  solar: "#f9d002"
  hydro: "#0079c1"
  cascade: "#46caf0"
  fossil: "#f6986b"
  PHS: "#4ca1d3"
  battery: "#ea581e"
  demand_flex: "magenta"

nice_names:
  nuclear: "Nuclear"
  biomass: "Biomass"
  interconnector: "Interconnector"
  onwind: "Onshore Wind"
  offwind: "Offshore Wind"
  solar: "Solar"
  hydro: "Hydropower"
  cascade: "Cascading Hydro"
  fossil: "Natural Gas and Coal"
  PHS: "Pumped Hydro Storage"
  battery: "Battery"
  demand_flex: "Flexible Demand"

countries_cost_slopes: # data-driven values taken from Fig 3 in Mendes et al. (2024) 'EuroMod: Modelling European power markets...'
  Belgium: 7.75 # EUR/GW
  Denmark: 6.28 # EUR/GW
  France: 0.94 # EUR/GW
  Ireland: 5.5 # EUR/GW (copied value from DK, and scaled by population; data missing in paper)
  Netherlands: 4.00 # EUR/GW
  Norway: 1.85 # EUR/GW
